import type { User, Venue, Booking, MaintenanceTask, DashboardKPIs, ReportData, VenueEvaluation, University, Notification, BookingPurpose } from './types';

export const currentUser: User = {
  id: '1',
  name: 'علی احمدی',
  email: 'ali.ahmadi@university.ac.ir',
  role: 'admin_national',
  avatar: '/avatars/user.jpg',
};

export const mockUniversities: University[] = [
  { id: 'u1', name: 'University of Tehran', nameFa: 'دانشگاه تهران', city: 'تهران', province: 'تهران' },
  { id: 'u2', name: 'Sharif University', nameFa: 'دانشگاه شریف', city: 'تهران', province: 'تهران' },
  { id: 'u3', name: 'Amirkabir University', nameFa: 'دانشگاه امیرکبیر', city: 'تهران', province: 'تهران' },
  { id: 'u4', name: 'Isfahan University', nameFa: 'دانشگاه اصفهان', city: 'اصفهان', province: 'اصفهان' },
  { id: 'u5', name: 'Shiraz University', nameFa: 'دانشگاه شیراز', city: 'شیراز', province: 'فارس' },
  { id: 'u6', name: 'Tabriz University', nameFa: 'دانشگاه تبریز', city: 'تبریز', province: 'آذربایجان شرقی' },
];

const defaultOperatingHours = [
  { day: 'Saturday', dayFa: 'شنبه', open: '06:00', close: '22:00', isOpen: true },
  { day: 'Sunday', dayFa: 'یکشنبه', open: '06:00', close: '22:00', isOpen: true },
  { day: 'Monday', dayFa: 'دوشنبه', open: '06:00', close: '22:00', isOpen: true },
  { day: 'Tuesday', dayFa: 'سه‌شنبه', open: '06:00', close: '22:00', isOpen: true },
  { day: 'Wednesday', dayFa: 'چهارشنبه', open: '06:00', close: '22:00', isOpen: true },
  { day: 'Thursday', dayFa: 'پنجشنبه', open: '08:00', close: '20:00', isOpen: true },
  { day: 'Friday', dayFa: 'جمعه', open: '08:00', close: '18:00', isOpen: false },
];

const defaultRules = [
  'رعایت نظم و انضباط',
  'استفاده از لباس ورزشی مناسب',
  'رعایت بهداشت فردی',
  'ممنوعیت مصرف مواد غذایی در محل',
  'رعایت ساعات حضور',
];

export const mockVenues: Venue[] = [
  {
    id: '1',
    name: 'Olympic Stadium',
    nameFa: 'ورزشگاه المپیک',
    type: 'stadium',
    status: 'active',
    capacity: 25000,
    area: 45000,
    location: {
      address: 'University Campus, Building A',
      addressFa: 'پردیس دانشگاه، ساختمان الف',
      lat: 35.6892,
      lng: 51.3890,
      city: 'تهران',
      province: 'تهران',
    },
    amenities: ['Parking', 'Locker Rooms', 'First Aid', 'Lighting', 'Sound System'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: true,
      ac: false,
      wifi: true,
      accessibility: true,
      cafe: true,
      equipmentRental: false,
      seating: true,
    },
    images: ['/venues/stadium-1.jpg', '/venues/stadium-2.jpg', '/venues/stadium-3.jpg'],
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    utilizationRate: 78,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '021-12345678',
    contactEmail: 'stadium@tehran.ac.ir',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '2',
    name: 'Indoor Sports Hall',
    nameFa: 'سالن ورزشی سرپوشیده',
    type: 'gym',
    status: 'active',
    capacity: 2000,
    area: 3500,
    location: {
      address: 'Sports Complex, Zone B',
      addressFa: 'مجموعه ورزشی، منطقه ب',
      lat: 35.6920,
      lng: 51.3920,
      city: 'تهران',
      province: 'تهران',
    },
    amenities: ['Locker Rooms', 'Showers', 'Equipment Storage', 'AC'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: true,
      ac: true,
      wifi: true,
      accessibility: true,
      cafe: false,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/gym-1.jpg', '/venues/gym-2.jpg'],
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    utilizationRate: 92,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '021-87654321',
    contactEmail: 'gym@tehran.ac.ir',
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: '3',
    name: 'Swimming Complex',
    nameFa: 'مجموعه آبی',
    type: 'pool',
    status: 'maintenance',
    capacity: 500,
    area: 2500,
    location: {
      address: 'Aquatic Center',
      addressFa: 'مرکز آبی',
      lat: 35.6880,
      lng: 51.3850,
      city: 'تهران',
      province: 'تهران',
    },
    amenities: ['Locker Rooms', 'Sauna', 'Diving Boards', 'Lifeguard'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: false,
      ac: true,
      wifi: false,
      accessibility: true,
      cafe: true,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/pool-1.jpg', '/venues/pool-2.jpg', '/venues/pool-3.jpg'],
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    utilizationRate: 45,
    operatingHours: defaultOperatingHours,
    rules: [...defaultRules, 'استفاده از کلاه شنا الزامی است', 'دوش قبل از ورود به استخر'],
    rulesFa: [...defaultRules, 'استفاده از کلاه شنا الزامی است', 'دوش قبل از ورود به استخر'],
    contactPhone: '021-11223344',
    contactEmail: 'pool@tehran.ac.ir',
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2024-03-22'),
  },
  {
    id: '4',
    name: 'Tennis Courts',
    nameFa: 'زمین‌های تنیس',
    type: 'court',
    status: 'active',
    capacity: 200,
    area: 1200,
    location: {
      address: 'Racquet Sports Area',
      addressFa: 'منطقه ورزش‌های راکتی',
      lat: 35.6910,
      lng: 51.3880,
      city: 'تهران',
      province: 'تهران',
    },
    amenities: ['Night Lighting', 'Equipment Rental', 'Seating'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: false,
      lighting: true,
      soundSystem: false,
      ac: false,
      wifi: true,
      accessibility: false,
      cafe: false,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/tennis-1.jpg'],
    universityId: 'u2',
    universityName: 'دانشگاه شریف',
    utilizationRate: 65,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '021-55667788',
    contactEmail: 'tennis@sharif.ac.ir',
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '5',
    name: 'Football Field',
    nameFa: 'زمین فوتبال',
    type: 'field',
    status: 'active',
    capacity: 5000,
    area: 8000,
    location: {
      address: 'Main Sports Ground',
      addressFa: 'زمین ورزشی اصلی',
      lat: 35.6900,
      lng: 51.3900,
      city: 'تهران',
      province: 'تهران',
    },
    amenities: ['Grass Turf', 'Goal Posts', 'Benches', 'Floodlights'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: true,
      ac: false,
      wifi: false,
      accessibility: true,
      cafe: false,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/football-1.jpg', '/venues/football-2.jpg'],
    universityId: 'u2',
    universityName: 'دانشگاه شریف',
    utilizationRate: 85,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '021-99887766',
    contactEmail: 'football@sharif.ac.ir',
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2024-03-21'),
  },
  {
    id: '6',
    name: 'Athletics Track',
    nameFa: 'پیست دوومیدانی',
    type: 'track',
    status: 'active',
    capacity: 3000,
    area: 12000,
    location: {
      address: 'Track and Field Complex',
      addressFa: 'مجموعه دوومیدانی',
      lat: 35.6870,
      lng: 51.3870,
      city: 'تهران',
      province: 'تهران',
    },
    amenities: ['8 Lanes', 'Long Jump Pit', 'Shot Put Area', 'Timing System'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: true,
      ac: false,
      wifi: true,
      accessibility: true,
      cafe: true,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/track-1.jpg'],
    universityId: 'u3',
    universityName: 'دانشگاه امیرکبیر',
    utilizationRate: 72,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '021-33445566',
    contactEmail: 'track@aut.ac.ir',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-03-19'),
  },
  {
    id: '7',
    name: 'Basketball Arena',
    nameFa: 'سالن بسکتبال',
    type: 'arena',
    status: 'reserved',
    capacity: 4500,
    area: 5000,
    location: {
      address: 'Sports Arena Complex',
      addressFa: 'مجموعه آرنای ورزشی',
      lat: 32.6546,
      lng: 51.6680,
      city: 'اصفهان',
      province: 'اصفهان',
    },
    amenities: ['Professional Courts', 'Scoreboards', 'VIP Seating', 'Press Room'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: true,
      ac: true,
      wifi: true,
      accessibility: true,
      cafe: true,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/basketball-1.jpg', '/venues/basketball-2.jpg'],
    universityId: 'u4',
    universityName: 'دانشگاه اصفهان',
    utilizationRate: 88,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '031-12345678',
    contactEmail: 'arena@isfahan.ac.ir',
    createdAt: new Date('2023-07-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '8',
    name: 'Volleyball Hall',
    nameFa: 'سالن والیبال',
    type: 'gym',
    status: 'active',
    capacity: 1500,
    area: 2800,
    location: {
      address: 'Indoor Sports Building',
      addressFa: 'ساختمان ورزش‌های سرپوشیده',
      lat: 29.6168,
      lng: 52.5388,
      city: 'شیراز',
      province: 'فارس',
    },
    amenities: ['Multiple Courts', 'Electronic Scoreboards', 'Training Equipment'],
    facilities: {
      parking: true,
      lockerRooms: true,
      showers: true,
      firstAid: true,
      lighting: true,
      soundSystem: true,
      ac: true,
      wifi: true,
      accessibility: false,
      cafe: false,
      equipmentRental: true,
      seating: true,
    },
    images: ['/venues/volleyball-1.jpg'],
    universityId: 'u5',
    universityName: 'دانشگاه شیراز',
    utilizationRate: 76,
    operatingHours: defaultOperatingHours,
    rules: defaultRules,
    rulesFa: defaultRules,
    contactPhone: '071-87654321',
    contactEmail: 'volleyball@shirazu.ac.ir',
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2024-03-18'),
  },
];

export const mockEvaluations: VenueEvaluation[] = [
  { id: 'e1', venueId: '1', userId: 'u1', userName: 'محمد رضایی', rating: 5, comment: 'مکان عالی با امکانات کامل', date: new Date('2024-03-15') },
  { id: 'e2', venueId: '1', userId: 'u2', userName: 'زهرا احمدی', rating: 4, comment: 'تجهیزات خوب، نظافت می‌تونه بهتر باشه', date: new Date('2024-03-10') },
  { id: 'e3', venueId: '1', userId: 'u3', userName: 'علی کریمی', rating: 5, comment: 'بهترین ورزشگاه دانشگاه', date: new Date('2024-03-05') },
  { id: 'e4', venueId: '2', userId: 'u1', userName: 'محمد رضایی', rating: 4, comment: 'سالن تمیز و مجهز', date: new Date('2024-03-12') },
  { id: 'e5', venueId: '2', userId: 'u4', userName: 'سارا محمدی', rating: 5, comment: 'عالی برای تمرینات تیمی', date: new Date('2024-03-08') },
  { id: 'e6', venueId: '3', userId: 'u2', userName: 'زهرا احمدی', rating: 3, comment: 'نیاز به تعمیرات دارد', date: new Date('2024-02-28') },
  { id: 'e7', venueId: '4', userId: 'u5', userName: 'رضا حسینی', rating: 4, comment: 'زمین‌های با کیفیت', date: new Date('2024-03-14') },
  { id: 'e8', venueId: '5', userId: 'u3', userName: 'علی کریمی', rating: 5, comment: 'چمن طبیعی فوق‌العاده', date: new Date('2024-03-11') },
];

// Generate dates relative to today for realistic booking data
const today = new Date();
const getRelativeDate = (daysOffset: number, hours: number = 0, minutes: number = 0) => {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  date.setHours(hours, minutes, 0, 0);
  return date;
};

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    venueId: '1',
    venueName: 'ورزشگاه المپیک',
    venueType: 'stadium',
    userId: 'u1',
    userName: 'تیم فوتبال دانشگاه',
    userEmail: 'football@tehran.ac.ir',
    userPhone: '09121234567',
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    startTime: getRelativeDate(0, 10, 0),
    endTime: getRelativeDate(0, 12, 0),
    purpose: 'training',
    purposeDetail: 'تمرین هفتگی تیم فوتبال',
    status: 'approved',
    attendees: 25,
    equipmentNeeded: ['توپ فوتبال', 'مانع تمرینی'],
    recurrence: 'weekly',
    recurrenceEnd: getRelativeDate(60),
    approvedBy: 'مدیر ورزشی',
    approvedAt: getRelativeDate(-2),
    createdAt: getRelativeDate(-5),
    updatedAt: getRelativeDate(-2),
  },
  {
    id: 'b2',
    venueId: '2',
    venueName: 'سالن ورزشی سرپوشیده',
    venueType: 'gym',
    userId: 'u2',
    userName: 'کلاس یوگا',
    userEmail: 'yoga@tehran.ac.ir',
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    startTime: getRelativeDate(0, 14, 0),
    endTime: getRelativeDate(0, 16, 0),
    purpose: 'class',
    purposeDetail: 'کلاس گروهی یوگا برای دانشجویان',
    status: 'pending',
    attendees: 30,
    equipmentNeeded: ['مت یوگا'],
    recurrence: 'weekly',
    createdAt: getRelativeDate(-1),
  },
  {
    id: 'b3',
    venueId: '4',
    venueName: 'زمین‌های تنیس',
    venueType: 'court',
    userId: 'u3',
    userName: 'باشگاه تنیس',
    userEmail: 'tennis@sharif.ac.ir',
    universityId: 'u2',
    universityName: 'دانشگاه شریف',
    startTime: getRelativeDate(1, 8, 0),
    endTime: getRelativeDate(1, 10, 0),
    purpose: 'competition',
    purposeDetail: 'مسابقه دوستانه بین دانشگاهی',
    status: 'approved',
    attendees: 8,
    equipmentNeeded: ['راکت', 'توپ تنیس'],
    recurrence: 'none',
    approvedBy: 'مدیر ورزشی شریف',
    approvedAt: getRelativeDate(-3),
    createdAt: getRelativeDate(-7),
  },
  {
    id: 'b4',
    venueId: '5',
    venueName: 'زمین فوتبال',
    venueType: 'field',
    userId: 'u4',
    userName: 'لیگ دانشجویی',
    userEmail: 'league@sharif.ac.ir',
    universityId: 'u2',
    universityName: 'دانشگاه شریف',
    startTime: getRelativeDate(2, 16, 0),
    endTime: getRelativeDate(2, 18, 0),
    purpose: 'competition',
    purposeDetail: 'بازی هفته سوم لیگ دانشجویی',
    status: 'pending',
    attendees: 50,
    recurrence: 'none',
    createdAt: getRelativeDate(-2),
  },
  {
    id: 'b5',
    venueId: '6',
    venueName: 'پیست دوومیدانی',
    venueType: 'track',
    userId: 'u5',
    userName: 'تیم دوومیدانی',
    userEmail: 'track@aut.ac.ir',
    universityId: 'u3',
    universityName: 'دانشگاه امیرکبیر',
    startTime: getRelativeDate(3, 6, 0),
    endTime: getRelativeDate(3, 8, 0),
    purpose: 'training',
    purposeDetail: 'تمرین صبحگاهی تیم دوومیدانی',
    status: 'approved',
    attendees: 15,
    recurrence: 'daily',
    recurrenceEnd: getRelativeDate(30),
    approvedBy: 'مدیر ورزشی امیرکبیر',
    approvedAt: getRelativeDate(-5),
    createdAt: getRelativeDate(-10),
  },
  {
    id: 'b6',
    venueId: '1',
    venueName: 'ورزشگاه المپیک',
    venueType: 'stadium',
    userId: 'u6',
    userName: 'مسابقات بین‌دانشگاهی',
    userEmail: 'events@university.ac.ir',
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    startTime: getRelativeDate(4, 9, 0),
    endTime: getRelativeDate(4, 17, 0),
    purpose: 'event',
    purposeDetail: 'مسابقات قهرمانی فوتبال بین دانشگاه‌های کشور',
    status: 'approved',
    attendees: 500,
    equipmentNeeded: ['سیستم صوتی', 'تابلو امتیازات'],
    recurrence: 'none',
    approvedBy: 'معاون ورزشی وزارت',
    approvedAt: getRelativeDate(-15),
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'b7',
    venueId: '2',
    venueName: 'سالن ورزشی سرپوشیده',
    venueType: 'gym',
    userId: 'u7',
    userName: 'کلاس ایروبیک',
    userEmail: 'aerobic@tehran.ac.ir',
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    startTime: getRelativeDate(0, 8, 0),
    endTime: getRelativeDate(0, 9, 30),
    purpose: 'class',
    purposeDetail: 'کلاس ایروبیک صبحگاهی',
    status: 'approved',
    attendees: 40,
    recurrence: 'weekly',
    approvedBy: 'مدیر سالن',
    approvedAt: getRelativeDate(-7),
    createdAt: getRelativeDate(-14),
  },
  {
    id: 'b8',
    venueId: '7',
    venueName: 'سالن بسکتبال',
    venueType: 'arena',
    userId: 'u8',
    userName: 'تیم بسکتبال اصفهان',
    userEmail: 'basketball@isfahan.ac.ir',
    universityId: 'u4',
    universityName: 'دانشگاه اصفهان',
    startTime: getRelativeDate(1, 15, 0),
    endTime: getRelativeDate(1, 17, 0),
    purpose: 'training',
    purposeDetail: 'تمرین تیم بسکتبال',
    status: 'rejected',
    attendees: 20,
    recurrence: 'none',
    rejectionReason: 'تداخل با مسابقات رسمی',
    createdAt: getRelativeDate(-3),
  },
  {
    id: 'b9',
    venueId: '8',
    venueName: 'سالن والیبال',
    venueType: 'gym',
    userId: 'u9',
    userName: 'تیم والیبال شیراز',
    userEmail: 'volleyball@shirazu.ac.ir',
    universityId: 'u5',
    universityName: 'دانشگاه شیراز',
    startTime: getRelativeDate(0, 18, 0),
    endTime: getRelativeDate(0, 20, 0),
    purpose: 'training',
    purposeDetail: 'تمرین تیم والیبال',
    status: 'approved',
    attendees: 18,
    recurrence: 'weekly',
    approvedBy: 'مدیر ورزشی شیراز',
    approvedAt: getRelativeDate(-4),
    createdAt: getRelativeDate(-8),
  },
  {
    id: 'b10',
    venueId: '1',
    venueName: 'ورزشگاه المپیک',
    venueType: 'stadium',
    userId: 'u10',
    userName: 'رویداد خیریه',
    userEmail: 'charity@ngo.org',
    startTime: getRelativeDate(7, 10, 0),
    endTime: getRelativeDate(7, 18, 0),
    purpose: 'event',
    purposeDetail: 'مسابقه فوتبال خیریه',
    status: 'pending',
    attendees: 1000,
    equipmentNeeded: ['سیستم صوتی', 'صندلی اضافه', 'چادر'],
    recurrence: 'none',
    createdAt: getRelativeDate(-1),
  },
  {
    id: 'b11',
    venueId: '2',
    venueName: 'سالن ورزشی سرپوشیده',
    venueType: 'gym',
    userId: 'u11',
    userName: 'امتحان عملی تربیت بدنی',
    userEmail: 'pe@tehran.ac.ir',
    universityId: 'u1',
    universityName: 'دانشگاه تهران',
    startTime: getRelativeDate(5, 8, 0),
    endTime: getRelativeDate(5, 12, 0),
    purpose: 'class',
    purposeDetail: 'امتحان پایان ترم درس تربیت بدنی',
    status: 'approved',
    attendees: 100,
    recurrence: 'none',
    approvedBy: 'معاون آموزشی',
    approvedAt: getRelativeDate(-10),
    createdAt: getRelativeDate(-20),
  },
  {
    id: 'b12',
    venueId: '4',
    venueName: 'زمین‌های تنیس',
    venueType: 'court',
    userId: 'u12',
    userName: 'کلاس آموزش تنیس',
    userEmail: 'tennis-class@sharif.ac.ir',
    universityId: 'u2',
    universityName: 'دانشگاه شریف',
    startTime: getRelativeDate(0, 16, 0),
    endTime: getRelativeDate(0, 18, 0),
    purpose: 'class',
    purposeDetail: 'کلاس آموزش مبتدی تنیس',
    status: 'approved',
    attendees: 12,
    equipmentNeeded: ['راکت آموزشی', 'توپ تمرینی'],
    recurrence: 'weekly',
    approvedBy: 'مربی تنیس',
    approvedAt: getRelativeDate(-5),
    createdAt: getRelativeDate(-12),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    type: 'booking_approved',
    title: 'رزرو تأیید شد',
    message: 'رزرو شما برای ورزشگاه المپیک در تاریخ ۵ فروردین تأیید شد.',
    read: false,
    bookingId: 'b1',
    createdAt: getRelativeDate(-2),
  },
  {
    id: 'n2',
    userId: 'u1',
    type: 'booking_reminder',
    title: 'یادآوری رزرو',
    message: 'رزرو شما برای فردا ساعت ۱۰:۰۰ در ورزشگاه المپیک است.',
    read: false,
    bookingId: 'b1',
    createdAt: getRelativeDate(-1),
  },
  {
    id: 'n3',
    userId: 'u2',
    type: 'booking_created',
    title: 'درخواست رزرو ثبت شد',
    message: 'درخواست رزرو شما برای سالن ورزشی سرپوشیده در انتظار تأیید است.',
    read: true,
    bookingId: 'b2',
    createdAt: getRelativeDate(-1),
  },
  {
    id: 'n4',
    userId: 'u8',
    type: 'booking_rejected',
    title: 'رزرو رد شد',
    message: 'متأسفانه رزرو شما برای سالن بسکتبال به دلیل تداخل با مسابقات رسمی رد شد.',
    read: false,
    bookingId: 'b8',
    createdAt: getRelativeDate(-3),
  },
  {
    id: 'n5',
    userId: 'u1',
    type: 'maintenance_alert',
    title: 'هشدار تعمیرات',
    message: 'مجموعه آبی تا اطلاع ثانوی در دست تعمیرات است.',
    read: true,
    createdAt: getRelativeDate(-5),
  },
];

export const mockMaintenanceTasks: MaintenanceTask[] = [
  {
    id: 'm1',
    venueId: '3',
    venueName: 'مجموعه آبی',
    title: 'Pool Water Treatment',
    titleFa: 'تصفیه آب استخر',
    description: 'بررسی و تنظیم سیستم تصفیه آب',
    type: 'preventive',
    status: 'in_progress',
    priority: 'high',
    assignedTo: 'حسن رضایی',
    scheduledDate: new Date('2024-03-23'),
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'm2',
    venueId: '1',
    venueName: 'ورزشگاه المپیک',
    title: 'Lighting System Check',
    titleFa: 'بازرسی سیستم روشنایی',
    description: 'بررسی و تعویض لامپ‌های معیوب',
    type: 'inspection',
    status: 'scheduled',
    priority: 'medium',
    assignedTo: 'محمد کریمی',
    scheduledDate: new Date('2024-03-28'),
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'm3',
    venueId: '2',
    venueName: 'سالن ورزشی سرپوشیده',
    title: 'Floor Maintenance',
    titleFa: 'نگهداری کف سالن',
    description: 'پولیش و تمیزکاری کف چوبی',
    type: 'preventive',
    status: 'scheduled',
    priority: 'low',
    assignedTo: 'رضا علوی',
    scheduledDate: new Date('2024-03-30'),
    createdAt: new Date('2024-03-18'),
  },
  {
    id: 'm4',
    venueId: '5',
    venueName: 'زمین فوتبال',
    title: 'Turf Repair',
    titleFa: 'تعمیر چمن',
    description: 'ترمیم نقاط آسیب‌دیده چمن',
    type: 'corrective',
    status: 'overdue',
    priority: 'critical',
    assignedTo: 'امیر حسینی',
    scheduledDate: new Date('2024-03-15'),
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'm5',
    venueId: '1',
    venueName: 'ورزشگاه المپیک',
    title: 'Seat Repair',
    titleFa: 'تعمیر صن��لی‌ها',
    description: 'تعویض صندلی‌های شکسته ردیف A',
    type: 'corrective',
    status: 'completed',
    priority: 'medium',
    assignedTo: 'محمد کریمی',
    scheduledDate: new Date('2024-03-10'),
    completedDate: new Date('2024-03-12'),
    cost: 15000000,
    createdAt: new Date('2024-03-01'),
  },
];

export const mockDashboardKPIs: DashboardKPIs = {
  totalVenues: 156,
  activeVenues: 142,
  utilizationRate: 73.5,
  occupancyToday: 68,
  maintenanceAlerts: 12,
  satisfactionScore: 4.6,
  totalBookings: 1247,
  pendingBookings: 23,
};

export const mockReportData: ReportData[] = [
  { period: 'فروردین', utilization: 65, bookings: 180, revenue: 45000000, maintenance: 8500000 },
  { period: 'اردیبهشت', utilization: 72, bookings: 210, revenue: 52000000, maintenance: 6200000 },
  { period: 'خرداد', utilization: 78, bookings: 245, revenue: 61000000, maintenance: 7800000 },
  { period: 'تیر', utilization: 82, bookings: 280, revenue: 68000000, maintenance: 5500000 },
  { period: 'مرداد', utilization: 85, bookings: 310, revenue: 75000000, maintenance: 9200000 },
  { period: 'شهریور', utilization: 79, bookings: 265, revenue: 64000000, maintenance: 11000000 },
];

export const toPersianDigits = (num: number | string): string => {
  const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
  return num.toString().replace(/[0-9]/g, (d) => persianDigits[parseInt(d)]);
};

export const formatPersianNumber = (num: number): string => {
  return toPersianDigits(num.toLocaleString('fa-IR'));
};

export const formatPersianDate = (date: Date): string => {
  return toPersianDigits(
    date.toLocaleDateString('fa-IR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
  );
};
